package com.fintrack.service.report;

import com.fintrack.domain.model.Transaction;
import com.fintrack.repository.TransactionRepository;
import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.awt.Color;
import com.lowagie.text.Rectangle;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class PdfExportService {

    private final TransactionRepository transactionRepository;

    private static final DateTimeFormatter DATE_FMT =
        DateTimeFormatter.ofPattern("dd MMM yyyy");

    public byte[] exportTransactionsPdf(UUID userId, LocalDate from, LocalDate to) {
        List<Transaction> transactions =
            transactionRepository.findByUserIdAndDateBetweenOrderByDateDesc(
                userId, from, to
            );

        try (
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
        ) {
            Document doc = new Document(PageSize.A4, 40, 40, 60, 40);
            PdfWriter.getInstance(doc, baos);
            doc.open();

            // ── Title ──────────────────────────────────────────────────────────
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Font subFont   = FontFactory.getFont(FontFactory.HELVETICA, 11,
                                                  Color.GRAY);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10,
                                                   Color.WHITE);
            Font cellFont   = FontFactory.getFont(FontFactory.HELVETICA, 10);

            doc.add(new Paragraph("FinTrack — Transaction Report", titleFont));
            doc.add(new Paragraph(
                from.format(DATE_FMT) + " → " + to.format(DATE_FMT), subFont
            ));
            doc.add(Chunk.NEWLINE);

            // ── Table ──────────────────────────────────────────────────────────
            float[] widths = {1.5f, 3f, 2f, 1.2f, 2f};
            PdfPTable table = new PdfPTable(widths);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10);

            // Header row
            String[] headers = {"Date", "Payee", "Category", "Type", "Amount"};
            for (String h : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(h, headerFont));
                cell.setBackgroundColor(new Color(17, 24, 39));
                cell.setPadding(8);
                cell.setBorder(Rectangle.NO_BORDER);
                table.addCell(cell);
            }

            // Data rows
            boolean alternate = false;
            for (Transaction t : transactions) {
                Color bg = alternate
                    ? new Color(249, 250, 251)
                    : Color.WHITE;
                alternate = !alternate;

                addCell(table, t.getDate().format(DATE_FMT), cellFont, bg);
                addCell(table, t.getPayee()    != null ? t.getPayee()              : "—", cellFont, bg);
                addCell(table, t.getCategory() != null ? t.getCategory().getName() : "—", cellFont, bg);
                addCell(table, t.getType().name(), cellFont, bg);

                // Colour the amount: green for income, red for expense
                boolean isIncome = t.getType().name().equals("INCOME");
                Font amtFont = FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD, 10,
                    isIncome ? new Color(22, 163, 74) : new Color(220, 38, 38)
                );
                String prefix = isIncome ? "+" : "-";
                PdfPCell amtCell = new PdfPCell(
                    new Phrase(prefix + "$" + t.getAmount().toPlainString(), amtFont)
                );
                amtCell.setBackgroundColor(bg);
                amtCell.setPadding(8);
                amtCell.setBorder(Rectangle.NO_BORDER);
                table.addCell(amtCell);
            }

            doc.add(table);

            // ── Summary ────────────────────────────────────────────────────────
            doc.add(Chunk.NEWLINE);
            Font summaryFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.GRAY);
            doc.add(new Paragraph(
                "Total transactions: " + transactions.size(), summaryFont
            ));
            doc.add(new Paragraph(
                "Generated by FinTrack · " + LocalDate.now().format(DATE_FMT), summaryFont
            ));

            doc.close();
            return baos.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    private void addCell(PdfPTable table, String text, Font font, Color bg) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(bg);
        cell.setPadding(8);
        cell.setBorder(Rectangle.NO_BORDER);
        table.addCell(cell);
    }
}